services:
  postgres:
    image: postgres:16
    container_name: csvmetrics-postgres
    environment:
      POSTGRES_DB: csvmetrics
      POSTGRES_USER: csvmetrics_user
      POSTGRES_PASSWORD: csvmetrics_pass
    ports:
      - "5432:5432"
    volumes:
      - csvmetrics_pgdata:/var/lib/postgresql/data

volumes:
  csvmetrics_pgdata: